### ISSUE TITLE
Configure dependabot for release branches

### ISSUE THREAD

**Issue by mynkow** [Elders/Cronus#162]
At the root of every project create a folder `.dependabot\config.yml`

Use the following content and be careful with the spaces because yml is very sensitive

```
version: 1
update_configs:
- package_manager: dotnet:nuget
  directory: /
  update_schedule: live
  default_reviewers:
  - Elders/cronus-team
  default_assignees:
  - mynkow
  target_branch: release-6.0.0
  default_labels:
  - dependencies
  allowed_updates:
  - match:
      update_type: all
      dependency_type: direct
  automerged_updates:
  - match:
      dependency_name: Cronus*
      dependency_type: all
      update_type: all
  - match:
      dependency_type: production
      update_type: all

```
